import { Suspect } from './types.js'

export const MIN_PLAYERS = 3
export const MAX_PLAYERS = 16

export const SUSPECTS: Suspect[] = [
  { id: 1, name: 'Гендальф', imageUrl: '../app/avatar-players/gendalf.jpg' },
  { id: 2, name: 'Баррин', imageUrl: '../app/avatar-players/barin.jpg' },
  { id: 3, name: 'Клайв', imageUrl: 'https://picsum.photos/seed/3/100/140' },
  { id: 4, name: 'Дейдра', imageUrl: 'https://picsum.photos/seed/4/100/140' },
  { id: 5, name: 'Эрнест', imageUrl: 'https://picsum.photos/seed/5/100/140' },
  { id: 6, name: 'Франклин', imageUrl: '../app/avatar-players/franklin.jpg' },
  { id: 7, name: 'Женева', imageUrl: 'https://picsum.photos/seed/7/100/140' },
  { id: 8, name: 'Горацио', imageUrl: 'https://picsum.photos/seed/8/100/140' },
  { id: 9, name: 'Ирма', imageUrl: 'https://picsum.photos/seed/9/100/140' },
  { id: 10, name: 'Джулиан', imageUrl: 'https://picsum.photos/seed/10/100/140' },
  { id: 11, name: 'Кристоф', imageUrl: 'https://picsum.photos/seed/11/100/140' },
  { id: 12, name: 'Линус', imageUrl: 'https://picsum.photos/seed/12/100/140' },
  { id: 13, name: 'Мэрион', imageUrl: 'https://picsum.photos/seed/13/100/140' },
  { id: 14, name: 'Нил', imageUrl: 'https://picsum.photos/seed/14/100/140' },
  { id: 15, name: 'Офелия', imageUrl: 'https://picsum.photos/seed/15/100/140' },
  { id: 16, name: 'Фиби', imageUrl: 'https://picsum.photos/seed/16/100/140' },
  { id: 17, name: 'Кунитон', imageUrl: 'https://picsum.photos/seed/17/100/140' },
  { id: 18, name: 'Райан', imageUrl: 'https://picsum.photos/seed/18/100/140' },
  { id: 19, name: 'Саймон', imageUrl: 'https://picsum.photos/seed/19/100/140' },
  { id: 20, name: 'Тревор', imageUrl: 'https://picsum.photos/seed/20/100/140' },
  { id: 21, name: 'Улисс', imageUrl: 'https://picsum.photos/seed/21/100/140' },
  { id: 22, name: 'Владимир', imageUrl: 'https://picsum.photos/seed/22/100/140' },
  { id: 23, name: 'Вильгей', imageUrl: 'https://picsum.photos/seed/23/100/140' },
  { id: 24, name: 'Ивонн', imageUrl: '../app/avatar-players/Ivonn.jpg' },
  { id: 25, name: 'Закари', imageUrl: 'https://picsum.photos/seed/25/100/140' },
  { id: 26, name: 'Брэнсон', imageUrl: 'https://picsum.photos/seed/26/100/140' },
  { id: 27, name: 'Кайрат', imageUrl: '../app/avatar-players/kairat.jpg' },
  { id: 28, name: 'Дарнелл', imageUrl: 'https://picsum.photos/seed/28/100/140' },
  { id: 29, name: 'Эвелин', imageUrl: 'https://picsum.photos/seed/29/100/140' },
  { id: 30, name: 'Педро', imageUrl: '../app/avatar-players/pedro.webp' },
  { id: 31, name: 'Рамён', imageUrl: '../app/avatar-players/ramon.webp' },
  { id: 32, name: 'Сюзанна', imageUrl: '../app/avatar-players/Suzanna.jpg' },
  { id: 33, name: 'Таша', imageUrl: 'https://picsum.photos/seed/33/100/140' },
  { id: 34, name: 'Ульбрехт', imageUrl: 'https://picsum.photos/seed/34/100/140' },
  { id: 35, name: 'Винсент', imageUrl: 'https://picsum.photos/seed/35/100/140' },
  { id: 36, name: 'Ванда', imageUrl: 'https://picsum.photos/seed/36/100/140' },
  { id: 37, name: 'Изольда', imageUrl: '../app/avatar-players/Izolda.jpg' },
  { id: 38, name: 'Грейс', imageUrl: 'https://picsum.photos/seed/38/100/140' },
  { id: 39, name: 'Хуюберт', imageUrl: 'https://picsum.photos/seed/39/100/140' },
  { id: 40, name: 'Иван', imageUrl: 'https://picsum.photos/seed/40/100/140' },
  { id: 41, name: 'Джек', imageUrl: 'https://picsum.photos/seed/41/100/140' },
  { id: 42, name: 'Кэтрин', imageUrl: 'https://picsum.photos/seed/42/100/140' },
  { id: 43, name: 'Линетт', imageUrl: 'https://picsum.photos/seed/43/100/140' },
  { id: 44, name: 'Маркус', imageUrl: 'https://picsum.photos/seed/44/100/140' },
  { id: 45, name: 'Натан', imageUrl: 'https://picsum.photos/seed/45/100/140' },
  { id: 46, name: 'Касым', imageUrl: 'https://picsum.photos/seed/46/100/140' },
  { id: 47, name: 'Флоренс', imageUrl: 'https://picsum.photos/seed/47/100/140' },
  { id: 48, name: 'Вэнс', imageUrl: 'https://picsum.photos/seed/48/100/140' },
  { id: 49, name: 'Уолтер', imageUrl: 'https://picsum.photos/seed/49/100/140' },
  { id: 50, name: 'Ксавье', imageUrl: 'https://picsum.photos/seed/50/100/140' },
]

export const WIN_CONDITION_TROPHIES = 3
export const LOSE_CONDITION_BOMBS = 3
